<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-JI6I8DAU" failures="1" tests="1" name="Register Page Test" time="9.158" errors="0" timestamp="2025-01-25T10:18:37 COT">
  <testcase classname="testingforomi.RegisterUser.RegisterPageTest" name="TestRegister" time="1.367">
    <failure type="java.lang.AssertionError" message="El mensaje de error se mostró.">
      <![CDATA[java.lang.AssertionError: El mensaje de error se mostró.
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at testingforomi.RegisterUser.RegisterPageTest.TestRegister(RegisterPageTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- TestRegister -->
</testsuite> <!-- Register Page Test -->
